# Single step sliding window

Given a time series, a single-step sliding window is a procedure that transforms the series into a set of overlapping input-output pairs.

Normally, we need 3 parameters to set up this set of sliding windows, these are:

- time_series: the actual time series
- window_size: the size of the training window
- horizon: how many time series points ahead we want to forecast

In the single-step case, each input window is associated with exactly one future value located horizon steps ahead.

## Example

Given the time series `[0,1,2,3,4,5,6,7,8,9]`, suppose we want windows that have size equal to 5, and we want to forecast 1 point ahead.

Then our sliding windows should be: `([0,1,2,3,4]`,`[5])`,`([1,2,3,4,5]`,`[6])`,`([2,3,4,5,6]`,`[7])`, `([3,4,5,6,7]`,`[8])`, `([4,5,6,7,8]`,`[9])`, in our case, this can be achieved by using the function `create_sliding_windows` in `\src\data\preprocessing.py` as shown below:

In [1]:
import numpy as np
from src.data.preprocess import create_sliding_windows

time_series = np.linspace(0,9,10)

X, y = create_sliding_windows(time_series,5,1)

for xi,yi in zip(X,y):
    print(xi,yi)



[0. 1. 2. 3. 4.] [5.]
[1. 2. 3. 4. 5.] [6.]
[2. 3. 4. 5. 6.] [7.]
[3. 4. 5. 6. 7.] [8.]
[4. 5. 6. 7. 8.] [9.]
